create table
  public.activities (
    id bigint generated by default as identity,
    name character varying not null,
    category_id bigint null,
    color character varying null,
    description text null,
    image character varying null,
    intern boolean not null,
    created_at timestamp with time zone not null default now(),
    status boolean not null default true,
    constraint activities_pkey primary key (id),
    constraint activities_category_id_fkey foreign key (category_id) references categories (id) on delete set null
  ) tablespace pg_default;