create table
  public.clients (
    id bigint generated by default as identity,
    avatar character varying null,
    name character varying not null,
    surname character varying not null,
    gender boolean not null,
    email character varying null,
    telephone character varying null,
    "dateOfBirth" date null,
    address character varying null,
    "firstContact" date null,
    sizes jsonb null,
    status smallint null,
    notes text null,
    constraint client_pkey primary key (id)
  ) tablespace pg_default;