create table
  public.collaborators (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    avatar character varying null,
    name character varying not null,
    surname character varying not null,
    gender boolean null,
    email character varying null,
    telephone character varying null,
    "dateOfBirth" date null,
    address character varying null,
    sizes jsonb null default '{"head": "", "pants": "", "shirt": "", "shoes": ""}'::jsonb,
    "firstContact" date null,
    status smallint not null,
    description text null,
    color character varying null,
    "linkSocial" jsonb null default '{"fb": "", "ig": "", "ln": "", "tk": "", "web": ""}'::jsonb,
    notes text null,
    constraint collaborators_pkey primary key (id)
  ) tablespace pg_default;