create table
  public.instances (
    id bigint generated by default as identity,
    name character varying not null,
    created_at timestamp with time zone not null default now(),
    level text not null,
    constraint activityOpen_pkey primary key (id)
  ) tablespace pg_default;