create table
  public.instance_activities (
    id bigint generated by default as identity,
    instance_id bigint not null,
    activity_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint instance_activities_pkey primary key (id),
    constraint instance_activities_activity_id_fkey foreign key (activity_id) references activities (id) on delete cascade,
    constraint instance_activities_instance_id_fkey foreign key (instance_id) references instances (id) on delete cascade
  ) tablespace pg_default;