create table
  public.client_instance (
    id bigint generated by default as identity,
    client_id bigint null,
    instance_id bigint null,
    created_at timestamp with time zone not null default now(),
    status boolean not null,
    constraint client_instance_pkey primary key (id),
    constraint client_instance_client_id_fkey foreign key (client_id) references clients (id) on delete cascade,
    constraint client_instance_instance_id_fkey foreign key (instance_id) references instances (id) on delete cascade
  ) tablespace pg_default;