create table
  public.collaborator_instance (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    collaborator_id bigint not null,
    instance_id bigint not null,
    constraint collaborator_istance_pkey primary key (id),
    constraint collaborator_instance_collaborator_id_fkey foreign key (collaborator_id) references collaborators (id) on delete cascade,
    constraint collaborator_instance_instance_id_fkey foreign key (instance_id) references instances (id) on delete cascade
  ) tablespace pg_default;