create table
  public.payments (
    id bigint generated by default as identity,
    type smallint not null,
    amount smallint not null,
    date date not null,
    notes text null,
    created_at timestamp with time zone not null default now(),
    client_id bigint null,
    collaborator_id bigint null,
    instance_id bigint null,
    amount_required smallint null,
    status bool not null
    constraint payments_pkey primary key (id),
    constraint payments_client_id_fkey foreign key (client_id) references clients (id) on delete restrict,
    constraint payments_collaborator_id_fkey foreign key (collaborator_id) references collaborators (id) on delete restrict,
    constraint payments_instance_id_fkey foreign key (instance_id) references instances (id) on delete restrict
  ) tablespace pg_default;